### ISSUE TITLE
Produce better error message if a subdirectory is not found inside a git repository (PACMAN-554)

### ISSUE THREAD

**Issue by igrr** [espressif/idf-component-manager#19]
### Related area

client

### Is your feature request related to a problem?

For a git dependency, if a subdirectory is specified via `path` and the subdirectory doesn't exist, an exception is raised. The error is not very easy to understand when you see it the first time:

https://github.com/espressif/esp-idf/issues/9929#issuecomment-1374886840

### Describe the solution you'd like

Produce a nice error message, explaining what the problem is and how to fix it, such as

> Error when installing dependency `lvgl`: subdirectory `lvgl/` specified at components/main/idf_component.yml:6 doesn't exist in the repository `https://github.com/lvgl/lvgl.git`

### I have checked existing list of Feature requests and I have provided enough information.

- [X] I confirm I have checked existing list of Feature requests and I have provided enough information.

**Comment by kumekay** [comment]
It was fixed in https://github.com/espressif/idf-component-manager/commit/798908a680205a0d00297ac4fb24bb0b485ebfe8
