### ISSUE TITLE
Documentation link is broken (PACMAN-624)

### ISSUE THREAD

**Issue by ljden** [espressif/idf-component-manager#30]
### The Component Manager version

repo main

### ESP-IDF Version

n/a

### python Version

n/a

### Operating System

N/A

### Browser (for https://components.espressif.com  Issues)

Firefox

### Description

Link in README does not load https://docs.espressif.com/projects/idf-component-manager/en/latest/
> The page isn’t redirecting properly
> An error occurred during a connection to docs.espressif.com.

### To Reproduce

```cpp
go to link
```

### Expected behaviour

link works

### I have checked existing issues and online Documentation

- [X] I confirm I have checked existing issues and online Documentation.

**Comment by kumekay** [comment]
@ljden Thank you for reporting. The documentation site is fixed now.
