### ISSUE TITLE
Check in poetry.lock into source control (PACMAN-637)

### ISSUE THREAD

**Issue by corpix** [espressif/idf-component-manager#34]
### Related area

git

### Is your feature request related to a problem?

There is no lock file in source control. This makes packaging this tool difficult (I do update this environment https://github.com/mirrexagon/nixpkgs-esp-dev)

### Describe the solution you'd like

I see `.gitignore` says `poetry.lock` was removed because of tests. Maybe this could be done during test environment preparation?

### I have checked existing list of Feature requests and I have provided enough information.

- [X] I confirm I have checked existing list of Feature requests and I have provided enough information.

**Comment by corpix** [comment]
Thanks for the reply!
I think I could, will try, thank you for the explanation!

**Comment by kumekay** [comment]
@corpix In a coming release of 2.0.0 we will remove setup.py, but still won't add a lock file. What is the main problem of packaging without a lock file?

**Comment by kumekay** [comment]
@corpix I would like to close this issue now, however you are welcome to reopen if you want to discuss this topic further.
