### ISSUE TITLE
Unknown targets error if component declare targets include esp32c6 and dependencies idf: ">=4.4" (PACMAN-644)

### ISSUE THREAD

**Issue by leeebo** [espressif/idf-component-manager#35]
### The Component Manager version

v1.2.3

### ESP-IDF Version

v4.4

### python Version

3.8

### Operating System

Ubuntu

### Description

We developed a component that needed to support both esp32, and esp32c6, and was required to support IDF 4.4 and IDF 5.0. When the user selects IDF5.0, the esp32 and esp32c6 builds will pass. But we also expect the esp32 compile to pass when the user selects IDF4.4, rather than reporting Unknown targets: esp32c6

### To Reproduce

```cpp
Add yml file with:

targets:
  - esp32
  - esp32c6
dependencies:
  idf: ">=4.4"


then build under IDF 4.4
```

### Expected behaviour

target esp32 can be built under IDF 4.4 without any CMake errors

### I have checked existing issues and online Documentation

- [X] I confirm I have checked existing issues and online Documentation.

**Comment by kumekay** [comment]
@leeebo This is fixed in https://github.com/espressif/idf-component-manager/releases/tag/v1.3.0
