### ISSUE TITLE
libmodbus (PACMAN-970)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/idf-component-manager#70]
### Related area

libmodbus

### Is your feature request related to a problem?

i have libmodbus running in ESP32: 
https://github.com/Fliegl-Agrartechnik-GmbH/libmodbus-examples-esp-idf

maybe it makes sense to add it to the Espressif Component manager ? 

### I have checked existing list of Feature requests and I have provided enough information.

- [X] I confirm I have checked existing list of Feature requests and I have provided enough information.

**Comment by igrr** [comment]
Hi @diplfranzhoepfinger, this repository hosts the python client of IDF component manager. The issue tracker is for the client only.

You are welcome to open a topic on esp32.com if you would like to get other developers' feedback on your idea.

**Comment by diplfranzhoepfinger** [comment]
done already: https://esp32.com/viewtopic.php?f=13&t=3302
