### ISSUE TITLE
how to support components name like this： core.display (PACMAN-1024)

### ISSUE THREAD

**Issue by goukisun** [espressif/idf-component-manager#77]
### The Component Manager version

v1.0.0

### ESP-IDF Version

v5.1.1

### python Version

3.11

### Operating System

win10/win11

### Description

when I use the component name "core.xx", the compilation reports an error

### To Reproduce

```cpp
Does it support such component naming?
```

### Expected behaviour

build failed

### I have checked existing issues and online Documentation

- [X] I confirm I have checked existing issues and online Documentation.

**Comment by kumekay** [comment]
@goukisun The possible names of the components are limited by the ESP-IDF build system. 


Current rules:

1.	Start and end with an alphanumeric character (a-z, A-Z, 0-9).
2.	Contain only alphanumeric characters, underscores (_), or hyphens (-).
3.	Avoid consecutive underscores or hyphens (__, --, _-, -_ are invalid).
4.	Ensure underscores or hyphens are surrounded by alphanumeric characters.
